print ("1 - Meu codigo Funciona, não sei como, mas funciona")
print ("2 - Gostei de aprender a programar, é muito divertido")
print ("3 - Hoje eu programo, amanhã eu descubro o que programei")
print ("4 - Existe talento nato, mas a prática é o que faz a diferença")
print ("5 - Programar é como aprender uma nova língua, no começo é difícil, mas depois se torna natural")
print ("6 - A programação é uma arte, e cada linha de código é uma pincelada na tela do software")
print ("7 - A programação é uma habilidade que pode ser aprendida por qualquer pessoa, basta dedicação e prática")
print ("8 - A programação é uma ferramenta poderosa que pode transformar ideias em realidade")
print ("9 - A programação é uma forma de pensar, que nos ajuda a resolver problemas de maneira lógica e eficiente")
print ("10 - A programação é uma habilidade cada vez mais importante no mundo atual, onde a tecnologia desempenha um papel fundamental")
print ("11 - A programação é uma forma de expressão criativa, que nos permite criar coisas incríveis com apenas algumas linhas de código")            
print ("12 - A programação é uma habilidade que nos permite criar soluções para problemas complexos, tornando o mundo um lugar melhor")
print ("13 - Gostei disso, vou continuar aprendendo e me aperfeiçoando cada vez mais")
print ("14 - 21 frases mesmo kkkk")
print ("15 - Mas bom de mais, mas mesmo assim")
print ("16 - A programação é uma habilidade que nos permite criar soluções para problemas complexos, tornando o mundo um lugar melhor")
print ("17 - Faz sentido, mas não sei se é verdade, mas é o que dizem")
print ("18 - A programação é um lugar de paz")
print ("19 - Vou fazer mais vezes isso aqui")
print ("20 - Espero que o professor nos ensine mais coisas legais, porque eu quero aprender muito mais sobre programação")
print ("21 - 21 frases que deram certo")